server{
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

    }

  # CRITICAL: Prevent static assets from falling back to index.html
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types; # Ensures application/javascript is used
        expires max;
        log_not_found off;
    }
    
    include /etc/nginx/extra-conf.d/*.conf;
}

