apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  password: YWtpZg==
  username: YWtpZg==
  mongodb_uri: bW9uZ29kYjovL2FraWY6YWtpZnBAbW9uZ29kYjoyNzAxNy9raW5kZXJnYXJ0ZW4/YXV0aFNvdXJjZT1hZG1pbiAtbgo=

  # mongodb://akif:akifp@mongodb:27017/kindergarten?authSource=admin