kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: student-log-persistance
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi